### ISSUE TITLE
test failures in halotools due to test runner incompatibility

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#17]
The package is failing the test suite when merging.  This is a astropy problem with the versioning of pytest.  @eteq is looking into this for us.

**Comment by eteq** [comment]
Oops, missed that this issue exists - https://github.com/astropy/halotools/commit/d62c292ec3a067e25e462e19bd60463284d7a13d *may* have fixed this... It's still failing but I think that's a real test failure rather than the testing system itself?

**Comment by eteq** [comment]
Also, for background on the solution: the original problem stems from the fact that the test runner invoked by ``python setup.py test`` actually imports astropy to run the tests.  Moreover, the latest ``astropy_helpers`` are *not* compatible with older versions of astropy.  Travis installs astropy from conda for halotools, but versions later than 4.1 are only available with numpy 1.9, and halotools was running its tests with numpy 1.8 up until d62c292.  

So that's super-convoluted why it failed, but the solution was basically just making sure that astropy is an up-to-date version when installed in travis.

To avoid this sort of thing in the future, astropy could do a few things: there could be more checks in the test runner to work around added feature, conda could be updated to include other numpy versions (@embray or @astrofrog - was this intentional, or just an oversight?), or the test runner should be fully integrated with the helpers (see astropy/astropy-helpers#73 for other discussion on this last point).

**Comment by aphearin** [comment]
@eteq - I'm not sure about this. Both on my local version of master, and on the local copy @duncandc has, neither of us get failures when running the test suite. 

Do keep in mind this is not urgent.

**Comment by astrofrog** [comment]
@eteq - we don't have control over conda versions of astropy, these are managed by the Continuum developers. They only build it with the latest Numpy version at the time. However, I've recently been investigating how to build conda packages and I've created a channel (``astrofrog``) from which you can install e.g. 1.0rc1 and if needed I could make it build 1.0 final (and other versions) with older versions of Numpy.

**Comment by eteq** [comment]
@astrofrog - ahh, gotcha - I thought we had been submitting some builds to them.

Also, as @embray just mentioned in astropy/astropy-helpers#73, he anticipated exactly this issue in astropy/astropy#3019, but it accidentally didn't end up in master.  So that should fix the problem directly, and then once thats in someone can update halotools' astropy_helpers to close this.
