### ISSUE TITLE
covariance matrix function

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#244]
create a general use covariance matrix calculation function given a matrix of N measurements.  Currently, tpcf_jackknife has its own function, but there is no reason why this could be removed and put somewhere more useful.

**Comment by duncandc** [comment]
this has been included in a new error_estimation_tools module in mock_obs_devel.  soon to be merged with master.

**Comment by givoltage** [comment]
Hi there, I searched in the master and the mock_obs_devel branches and couldn't find this general use function. Was it actually implemented? I'd like to calculate the covariance matrix for all the bin pairs from rp_pi_tpcf. Thanks.

**Comment by aphearin** [comment]
Sorry, @givoltage - it looks like @duncandc dropped his early ambitions to implement this feature. There is currently no code for jackknifing the `rp_pi_tpcf` function. For jackknifing, the only two functions currently supported are `tpcf_jackknife` and `wp_jackknife`. 

I think, but I am not sure, that it would be quite straightforward for `rp_pi_tpcf_jackknife` to be implemented using the same pattern recently used to implement `wp_jackknife`. @duncandc - would this be easy to do, or complicated for reasons I don't foresee?

On a closely related note, in a recent Slack conversation, @andrew-zentner told me that his student Kuan Wang had independently written code to solve the problem for completely generalized two-point function error estimation. @andrew-zentner - since there is now a specific feature request along these lines, do you know how far along Kuan's code is?

**Comment by duncandc** [comment]
This would be trivial to implement.  The workhorse behind wp_jackknife() is npairs_xy_z_jackknife().  The exact same function would also be called in a rp_pi_tpcf_jackknife() function.  I can add this to the list and probably have it done within the week.

On a related note, having a second version of every mock_observable that returns a jackknife covariance matrix may start to get unwieldy.  Maybe Kuan Wang has solved this problem.
