### ISSUE TITLE
Modify css file to truncate class docs

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#273]
As suggested by @yyao, it would be a bit cleaner to have only the methods summary on the page for a given class, and the docstring of the actual methods documented on a separate page.

**Comment by eteq** [comment]
@aphearin @yyao - if I understand this right, you're suggesting essentially that each class documentation page be split into *two* pages, is that right?  One with the methods docs and the other with just the list?

I think this is possible but not trivial because it probably requires some amount of hacking into ``autosummary`` to make two pages instead of one.  (Although *maybe* the autosummary templates can be split in this fashion? I'm not sure without looking into it more...) I don't think it would work to mess with the css itself, though - the autosummary templates give more fine-grained control for this sort of thing.

But can you clarify the motivation for this?  When I look at e.g. http://halotools.readthedocs.org/en/master/api/halotools.empirical_models.Moster13SmHm.html the first thing you always see is the summary, so I don't really see what the point is of it being on a separate page.

If the trouble is that the pages looked crammed together, it would be a lot easier to adjust the templates to inject some additional space between the sections (or even just the CSS could probably do that).

**Comment by aphearin** [comment]
If I understood @yyao correctly, the main motivation was to make the halotools docs look more like the numpy docs. So, there would actually be *many* more pages than even you described, @eteq. There would be a single page per class method. I have since reviewed many of the Halotools classes and now no longer agree that this is actually preferable. There are many very short, focused class methods that have very simple behavior, and it would be overkill to give them their own page. 

However, I still think @yyao has a point: each class' documentation really does get pretty crowded into a long page. And I think the hybrid solution you proposed could substantively help: adjusting the templates to having cleaner separation between the "methods summary" section and the "methods documentation" section would really help. Also, roughly equally importantly, the "methods documentation" section itself is really crowded and the distinct methods get crammed together. 

That being said, I think this falls very firmly in the category of "cosmetic" changes that should not have too much time spent on. If there are simple manipulations to the CSS that can accomplish part of the remedy, that would be perfectly sufficient in my opinion, and probably the best bang-for-the-buck.
