### ISSUE TITLE
Major history revision to the Halotools master branch

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#282]
At the time of this Issue, the astropy/master branch has had a major history revision that impacts all open Halotools branches. At some point along ago, I merged in a couple of ~20Mb files and deleted them. This was back before Duncan and I wrote the pair-counter, and we were experimenting with the one written by Manodeep. This inadvertently resulted in an unwanted expansion of the git history file size. I rewrote history this morning with the following command:

git filter-branch --force --index-filter  'git rm --cached --ignore-unmatch halotools/mock_observables/sinha_pairs/*.ff' --prune-empty --tag-name-filter cat -- --all

This fix was found by @eteq on https://help.github.com/articles/remove-sensitive-data

I then pushed directly to astropy/master. This decreased the size of the Halotools repo from 40Mb down to 7Mb. 

Thus all open branches need to be rebased on the new master. Though the simplest thing by far is for anyone with a copy of Halotools to simply re-clone master from scratch. There is no change to functionality whatsoever with this patch, so re-cloning is only necessary if you want your working copy to submit a PR to astropy/master. This is unfortunate, but needed to be done and was better addressed now than after the beta-release (or worse, after the v1 release). 

CC @duncandc , @surhudm , @yyao , @BenediktDiemer

**Comment by aphearin** [comment]
I'm not sure whether this would be overkill, but actually the *safest* thing would be to obliterate your copy on github entirely, and re-fork from the recently-updated master.

**Comment by eteq** [comment]
For any looking here, another approach to deal with your github forks (*not* your local copy, which is distinct from the github version) would be to just not have your fork be tied to master at all.  I generally prefer this approach *anyway*, because then you won't get confused between *your* master and the main repo's master.

The easiest way to do this is:
* make a new branch on your github repo called whatever you want (I use "staging").  You can do this either by pushing from a local branch to github, or via the github "new branch" web site interface.
* change the "default branch" to your new one ("staging") on the settings page of your github fork
* delete the master branch from your github fork (make sure you do this on *your* fork, not the main repo, if you have access to it...)
