### ISSUE TITLE
Negative galaxy-galaxy correlation function

### ISSUE THREAD

**Issue by mjvakili** [astropy/halotools#316]
mock_observables.tpcf() returns negative value for the first bin, and also it is not monotonically decreasing over the first few rbins.
 
I suspect that might be due to insufficient number of randoms in computation of the 2pcf estimator.

This is the outcome of model.mock.compute_galaxy_clustering():

(array([  0.12239095,   0.17719995,   0.25655347,   0.37144299,
          0.53778224,   0.77861137,   1.12728837,   1.63210958,
          2.36299934,   3.42119545,   4.95327193,   7.17144145,
         10.38294952,  15.03263208]),
 array([ -1.        ,   0.12760279,   3.68148708,  11.60978411,
         11.19051433,   7.99856754,   5.04833077,   3.03954944,
          1.80054104,   1.0243043 ,   0.6106042 ,   0.34611761,
          0.19264118,   0.10078104]))

**Comment by changhoonhahn** [comment]
I've been doing some tests on this issue with different r bins. I find that the issue mainly persists for r < 0.3.

If I specify r bin edges of
[  0.1          0.5          1.           1.2210553    1.49097605 ... ] 
the xi values from compute_galaxy_clustering are 
[ 9.61423222  7.83159952  5.06356391  4.03091415  3.00004464 ... ] . 
No negative values and monotonically decreasing.

On the other hand if I specify r bin edges of
[  0.1, 0.3, 1., 1.2210553, 1.49097605 ... ] 
the xi values from compute_galaxy_clustering are, 
[ 2.18375258, 8.19514426,  5.17546647,  3.92509287,  2.95110477 ... ]

**Comment by aphearin** [comment]
Xi = DD/RR - 1

RR is computed analytically, so that is not what's going on. A negative correlation function can, in principle, be a perfectly correct result (just look at the formula for the estimator). However, since you only see this in the inner bins, what is happening is just your point data happens to be sparse, so number counts are low due to random Poisson fluctuations. Make sense? Can you describe what problem this is causing for your code?

**Comment by changhoonhahn** [comment]
I see. It doesn't cause any problems with our code. The small scale behavior of the 2pcf was just unexpected.

**Comment by aphearin** [comment]
Right, ok, that makes sense as a possibly alarming source of confusion, and you're not the first users to hit this source of confusion.  I think documenting it is the only way to handle this properly, since I can't think of a robust way to automatically detect what's going on here (unless you have suggestions?)

Do you have any suggestions for how to properly document this? Where did you look to see if this had been documented? Or if you didn't look, that's ok, but where *might* you have looked for some comment on this? It's just that this is likely to come up again.

**Comment by mjvakili** [comment]
I have a general suggestion:
In the two-point correlation function documentations, it would be helpful to include examples that demonstrate the calculation of 2-point functions (tpcf, wp, monopole, and quadrupole) for mock galaxy catalogs generated by Halotools. 

I like the examples with randomly distributed set of points, and I find them useful for understanding how the underlying source-code works. But having examples that show the actual use of these two-point-functions in mock galaxy catalogs, would be more informative.

I'm not entirely sure if this was a relevant comment but I thought I'd bring it up.

**Comment by aphearin** [comment]
@mjvakili I agreed with your comment and left this issue open as a reminder to myself. I now have some pretty extensive documentation on this:

http://halotools.readthedocs.org/en/latest/quickstart_and_tutorials/tutorials/catalog_analysis/galcat_analysis/index.html

Does this seem sufficient? If not, what else would help clarify? If so, and you think this addresses your confusion, would you just close the issue?

**Comment by mjvakili** [comment]
@aphearin : Yes, this looks great. Thanks. I'm closing the issue. 
Sorry that my comment was not relevant to the title of the issue. I should have opened a different issue for this.
