### ISSUE TITLE
Create convenience functions for subvolume-based predictions

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#344]
I've got an implementation up on the following gist for how to do this. 

https://gist.github.com/aphearin/ea9104d4a798ae586965

I'm not sure how much/little of this should be incorporated into the repo, so I'd like some feedback. @duncandc , @mjvakili, @changhoonhahn, and @kilianbreathnach, let me know what y'all think and I'll take it into account while deciding how much of this should make it in.

**Comment by kilianbreathnach** [comment]
Hey Andrew, this looks great! I had originally tried building something similar but was using your idea of first setting a new column of subvolume id numbers in the halo table that I can then use to make a mask after choosing a random subvolume. I think this would be useful to add so that one doesn't have to recompute which halos are in the subvolume every time. I've made a notebook where I attempt an example of this here:

https://github.com/mjvakili/ccppabc/blob/master/halo/code/notebooks/subvol_sample.ipynb

**Comment by aphearin** [comment]
@kilianbreathnach , great, I'm glad the gist was clear. So even if the subvolume index were pre-computed, you'd still need to build a new boolean array mask with each random subvolume selection (although see below). So the only difference between the code on my gist and the code that would be written if the subvolume indices were pre-computed would be the following two lines:

```
mask = table['x'] > xmin & table['x'] < xmax & etc.
mask = table['subvol_id'] == randomid
```
So there is a little more computation time in the first line relative to the second, but my gut is that this difference is trivial relative to the clustering calculation. Are you finding otherwise?

The other option is that we could compute subvolume indices in advance, and also *pre-sort* the halo table according to the sub-volume index, storing the array of indices where each new subvolume begins. Then we'd only need to carry around an array serving as this lookup table. In fact, I use exactly this same trick when I build a rectangular tree in mock_observables. That would certainly be faster than building a mask, but again, I think the masking is a very minor contribution to the runtime, so the benefit of this code seems small relative to the intrinsic danger of introducing non-trivial bookkeeping. 

Maybe I mis-understood why you wanted to pre-compute the subvolumes?

**Comment by kilianbreathnach** [comment]
Aha yeah, you're right that it's a pretty small change in efficiency. I just found it convenient and easier to think about in this way, in particular so that I could also generate a set of random files for each subvolume with precomputed RR that I could store beforehand for use in the correlation calculations. The presorted halo table is a sweet idea. I found the masking to be somewhat time-consuming before but I'm realising that it must have been something that was up with my ipython instance and it is running much faster now :)

**Comment by aphearin** [comment]
Hmm, well your comment about your IPython instance makes me a little worried. Do you think the current algorithm was maxing out your ram?

If the masking is a time drain, the pre-sort is the solution, but I think we should avoid implementing that unless we need it. It's not hard, it's just an issue of not optimizing a problem unless it needs to be optimized.

**Comment by aphearin** [comment]
As for precomputed RR, why do you need to have a list stored beforehand for different subvolumes? They're just randoms, so the RR counts have nothing to do with the selected subvolumes.

**Comment by aphearin** [comment]
@kilianbreathnach, @mjvakili, @changhoonhahn - unless you object, I'd like to close this issue for now. I'd like to postpone adding this subvolume loop as a convenience feature until I have a better sense of how to handle the case where a full suite of simulations is populated, a closely related feature. Let me know if you have been finding it a big hassle to populate subvolumes, in which case I'll reconsider.

**Comment by mjvakili** [comment]
@aphearin - populating subvolumes is pretty straight forward now and it's not a hassle.

**Comment by aphearin** [comment]
Ok, good to know. In that case I'd rather not try to implement a convenience function whose API might change in the future. So I'll leave this to be done manually by the user for now. Thanks for the feedback.
