### ISSUE TITLE
Lack of scripts subdirectory when using pip install

### ISSUE THREAD

**Issue by cavestruz** [astropy/halotools#461]
>> pip install halotools 
does not include halotools/scripts, which is necessary for downloading the default halo catalog.

**Comment by aphearin** [comment]
@eteq - is this the intended behavior? I've never noticed this because I always install from a clone.

**Comment by eteq** [comment]
@cavestruz @aphearin - I just tested this now using conda, and if I do ``pip install halotools``, it *does* install the scripts in the appropriate place.  Is it possible the relevant bin directory isn't on your path, @cavestruz?  Or is there some other reason you are sure the scripts didn't get installed?

**Comment by aphearin** [comment]
@cavestruz - this turns out to just be an issue of poor documentation. If you install the package via `pip install`, it's true that the script is *not* located in `some/dir/site-packages/halotools/scripts`. However, the script is itself globally installed, so that if you cd into *any* directory on your machine and type, for example, `$ download_additional_halocat.py -h`, then the help message will print. Same goes for ` $ download_initial_halocat.py`. 

I will update the documentation to clear this up, thanks for raising the issue.

**Comment by cavestruz** [comment]
Hi Andrew - thanks for following up on that!

Best,
Camille
