### ISSUE TITLE
tpcf_jackknife requires randoms, but documentation says it is optional

### ISSUE THREAD

**Issue by mclaughlin6464** [astropy/halotools#497]
The tpcf_jackknife function requires 3 arguments: samples, rbins, and randoms. The docstring and docs say that randoms can be calculated if periodic boundary conditions are given. Randoms should be changed to a keyword arguement, but I couldn't figure out exactly what the default should be. There also should be, I suppose, some assertions that if randoms is the default than ensure a boxsize was passed in.

**Comment by aphearin** [comment]
Thanks for pointing this out, @mclaughlin6464. For `tpcf_jackknife`, the `randoms` input is not optional, despite what it says in the docstring. I just submitted a PR making the docstring correction. 

Even if applying PBCs, `randoms` are mandatory because the volume in which points are distributed is non-trivial. For a fully-filled periodic box, it is easy to analytically calculate how many pairs of random points there should be knowing only *Nran*; for the case of a box with a single subvolume removed, the analytical calculation is not straightforward. It can be done, but rather than work out all the geometry calculations for the different limits of sphere size and missing-subvolume location, it's a lot easier to just require randoms and be done with it. That makes the calculation slower than analytical randoms, of course, but since jackknife error estimation is never done on-the-fly in a performance-critical MCMC-type analysis, it seemed worth taking the performance hit for the sake of having a simple and robust result. 

FYI, I'm currently finishing up the overhaul of `mock_observables` in preparation for the `v0.2` upgrade; I completely understand why you found the control flow of `tpcf_jackknife` too complicated to follow - the current implementation is very confusing. PR #499 does not fix this, but I just raised #500 to remind me to do this before the next release.

**Comment by mclaughlin6464** [comment]
Follow-up question: Why put drawing random samples on the user? I'm having trouble imagining a use case where the user isn't just passing in a np.random.random((NRan, 3)).

**Comment by aphearin** [comment]
Watch out: those input randoms would only be correct for Lbox=1.

**Comment by mclaughlin6464** [comment]
Oh right, I mean to say `np.random.random((NRan, 3))*Lbox`

**Comment by aphearin** [comment]
Yes, though the fact that you made this casual mistake is convincing enough that I should include this in the code internals to protect against exactly this bug. So, in other words, point taken. I'm finishing up a branch that reworks all the argument-handling control flow of the tpcf functions; will merge it very soon and tag you when I do.

**Comment by aphearin** [comment]
Closing this issue as it was resolved by #507, but @mclaughlin6464 feel free to re-open and/or comment further if you think `tpcf_jackknife` hasn't been fixed properly.
