### ISSUE TITLE
mock_observables does not import due to ckdtree

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#54]
In the current version of the repo, the test suite passes, but the mock_observables sub-package fails to import. This seems to trace to ckdtree, which I thought we no longer were going to use, but I'm not sure what other routines may still be dependent on ckdtree. 

I think, but am not sure, that this is what is causing the ReadTheDocs build of the documentation to fail. So until @duncandc has a chance to try and fix this, then @eteq should ignore the RTD build problem.

**Comment by duncandc** [comment]
@aphearin @eteq I get the same problem when I try to import from my halotools directory.  This is not a problem with the ckdtree.  Any cython package will not import unless you are importing from a "built" halotools.  I find this very annoying, but I am not sure what the best way to fix this is.

Just to check.  @aphearin, if you run "python setup.py build" and "cd" into the build directory, can you import mock_observables?

**Comment by aphearin** [comment]
Nope. The code does not build on my machine. When I try to build it I get:

Parent module 'halotools.mock_observables.pair_counters.cpairs' not found while handling absolute import

Do you not get this, @duncandc ?

**Comment by aphearin** [comment]
It's worth noting here that this exact same error shows up in the RTD build failure, so @eteq - this may be the same error causing the docs problems:
https://readthedocs.org/builds/halotools/2739488/

**Comment by eteq** [comment]
@aphearin - this was strange to me... when *I* try to build commit ef91365 (which I think is the last one before you wiped the mock_observables ), it builds fine for me locally...

**Comment by eteq** [comment]
@duncandc re: the building thing: I'm not sure what you're saying you can't do that's annoying: if it's C code it *has* to be compiled, otherwise it won't work.  So what's the alternative to it being built?  Or do you mean you want to be able to import directly from the source code directory?  If the latter, there's two options: I usually just cd into "build/lib.xxx" and then test it from in there - basically the same as doing it in source aside from the need to "python setup.py build" to get it in there (which you need anyway if working on c code).  Or, if you really want it in the source directory, you can do this: ``python setup.py build_ext --inplace build`` which will copy over the "built" C extensions to the relevant places in the main source tree.  That's a bit more fragile because sometimes it gets confused about what's actually been built, but it usually works fine according to other people I know who use it.

**Comment by aphearin** [comment]
Mock_observables has been wiped clean. Let's start fresh, @duncandc .
