### ISSUE TITLE
expose `seed` keyword in HOD mock making for reproducible mocks

### ISSUE THREAD

**Issue by nickhand** [astropy/halotools#551]
For testing purposes, it would be useful if the random seed could be set from the `populate_mock` function of `HodModelFactory` .

It looks like the ``mc_occupation_*`` functions take a `seed` keyword, but I do not see an obvious way of passing in a value when populating mocks (outside of a hack-ish wrapping of those functions).

**Comment by nickhand** [comment]
@aphearin -- I've put together a quick hack that seems to do the trick in my specific case that just wraps the `mc_occupation_centrals` and `mc_occupation_satellites` functions as well as the `mc_pos`, `mc_radial_velocity`, `mc_solid_sphere` functions of the satellites profile, passing in the `seed` keyword. I'm happy to use that in the short term, so whatever timeline you prefer will work for me. Once you have something I'll happily help test out the feature.

**Comment by aphearin** [comment]
Ok, good to know you were able to write a workaround. 

This is sort of a brain burp, but for this purpose there is a particularly handy context manager within Astropy: `from astropy.utils.misc import NumpyRNGContext`. You can see example usage of it all over my test suite (e.g, halotools/mock_observables/two_point_clustering/tests/test_wp.py). Rather than have the Numpy seed be a fully global variable, this context manager sets the seed within its namespace and then resets the value to be whatever it was outside of the context. You should totally ignore this if you don't find it useful, just thought I'd mention it. That's the way I'll modify the source code when the time comes.  I'll try and properly implement this feature soon, keeping this issue open until I do.

**Comment by aphearin** [comment]
This should be resolved by #584. Please re-open if this is not what you had in mind, @nickhand.
