### ISSUE TITLE
cython building error

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#58]
@aphearin @eteq 

I get the following error when building a clean clone of halotools once I add a cython module:

"Cython must be installed to build from a git checkout."  

I do in fact have cython installed.

**Comment by aphearin** [comment]
Weird. Could you try adding 'cython' to the install_requires field of setup.py?

**Comment by duncandc** [comment]
no dice.  same error.

**Comment by eteq** [comment]
@duncandc - that is strange.  Is it possible you've got conflicting python installations?  Like it thinks cython isn't installed because it installed it in a place it can't see?

Can you push the commit in question up to some branch somewhere so that I can separately see if I get the same error?

**Comment by duncandc** [comment]
@eteq and @aphearin 

see merge latest request.

**Comment by aphearin** [comment]
Awesome. I'll test it asap.

**Comment by aphearin** [comment]
Ok, so I checked out the mock_obs_devel branch that @duncandc has up on his fork. The following works:

python setup.py build
from halotools import mock_observables

However, this seems to be because the __init__.py files are empty. I tested this with the following changes:

To halotools/mock_observables/__init__.py, I added:
    from .pair_counters import *

And to halotools/mock_observables/pair_counters/__init__.py, I added:
    from .sinha_pairs import *

With only these changes to the code, when I try to import the code I get:
    ImportError: No module named sinha_pairs_wrapper

This is a little perplexing, because the code apparently does compile and build. Any ideas @eteq ?

**Comment by duncandc** [comment]
I have noticed this odd import behavior.  The following works:

from halotools import mock_observables.pair_counters.sinha_pairs as pairs

Then you can count pairs with 
pairs.npairs()

**Comment by aphearin** [comment]
Huh. That's puzzling. Let's see if @eteq has experience with something like this before we merge.

**Comment by aphearin** [comment]
Also, I have not handled multiple simultaneous PRs before. Since @duncandc  submitted this PR, I have updated the master branch at least once, I think twice, with significant changes to the documentation. @eteq - is it safe to just use the github tools to merge directly, or should I locally clone from the branch on @duncandc 's fork, merge locally, and submit a new PR? What do y'all do in Astropy?

**Comment by duncandc** [comment]
I can do it on my machine.

**Comment by aphearin** [comment]
I don't mind doing it at all. I just want to know whether it's necessary to go through that rigamarole.

**Comment by eteq** [comment]
@duncandc - just so we're on the same page, you meant #63, right? (If you just type ``#63`` into a github comment it creates the link automatically so there's no ambiguity).

To answer @aphearin's question: if github is showing the "merge" button it's nearly always safe to merge (which is indeed the case for #63), because that means there are no files in conflict.  If there *is* a conflict, the merge button is greyed out.  In Astropy, the way we deal with that is that we have the submitter get the latest master and then do "git rebase master".  That basically re-writes history so that the new branch seems to be *starting* from the current master (rather than a past master).  The submitter will then have to deal with the conflicts as part of the rebase, but that's usually better because they usually know the code best.

**Comment by eteq** [comment]
Also, @duncandc and @aphearin - am I understanding right that the Cython building problem has gone away now?  If so,you might consider closing this issue and moving the conversation to #63, just to make that clearer. Or if you think this is ready to go of course you can just merge it and close this anyway.
