### ISSUE TITLE
support for anisotropic boxes in UserSuppliedHaloCatalog?

### ISSUE THREAD

**Issue by nickhand** [astropy/halotools#641]
It seems like it should be possible to make ``Lbox`` a more general 3-vector, instead of just a scalar? If this is something you're open to, I can take a look at a PR.

**Comment by aphearin** [comment]
Fortunately, all of the `mock_observables` functions were written to accept an input `period`, which can either be a scalar or length-3 sequence. And there are actually a relatively small number of places where `Lbox` is even used in either of the `empirical_models` or `sim_manager` sub-packages; I just ran a simple grep on `Lbox` and all appearances are either already compatible with distinct periodicities, or rather trivially changed to be compatible, so that is all good news, since it means that the `UserSuppliedHaloCatalog` requirement of a scalar can be relaxed without too much trouble (the requirement was never there for any particularly good reason). 

I won't be in a position to lead such a PR until the week of 23 January, but I could take a crack at it that week. If you need it sooner, I could certainly review and run tests on a PR sooner than that. On what timescale would you use this feature if it became available?

**Comment by nickhand** [comment]
Great, that's what it seemed from my quick grep on `Lbox` as well. There's no rush on my end to get this implemented -- nbodykit supports anisotropic boxes, so it would be nice to have the compatibility, but nearly all of the use cases for us are isotropic (as are for most people, I would assume). 

I think I should be able to get a PR together that relaxes the scalar requirement in `UserSuppliedHaloCatalog` in the next week or so for review.

**Comment by aphearin** [comment]
Closing this now that #652 has been merged.
