### ISSUE TITLE
TPCF API (jackknife errors)

### ISSUE THREAD

**Issue by duncandc** [astropy/halotools#70]
@aphearin Do we want to have a separate function to calculate a simple TPCF and the TPCF with jackknife errors?

options:
1.) separate functions (tpcf, tpcf_jackknife)
2.) only calculate TPCFs with errors
3.) one function with a complicated API (and code) that has it as an option.

**Comment by duncandc** [comment]
context: the jackknife calculation is more expensive.

**Comment by aphearin** [comment]
A) I understand why the jackknife calculation is both intrinsically more expensive and complicated. It makes sense that you are hesitant muddy up an otherwise pretty tpcf function. 

B) I think a mix of the (1) & (3) is probably best. Let me know what you think of the following alternative option:

(4) An entirely separate function computes jackknife_tpcf. However, within the function named tpcf, there is a boolean-valued optional keyword argument called 'jackknife_errors' (False by default). If this keyword is set to True, it entirely by-passes the tpcf function and calls tpcf_jackknife. 

This solution is a little guilty of the "spaghetti-code" criticism, but I don't mind this sort of thing for straightforward, one-step branchings, provided they are well documented with both docstrings and in-line comments. 

Your opinion?
