### ISSUE TITLE
Cannot make set() of dict()

### ISSUE THREAD

**Issue by kilianbreathnach** [astropy/halotools#714]
There is a problem with the code on line 737 in hod_model_factory.py in build_init_param_dict:
   ` intersection = set(self.param_dict) & set(component_model.param_dict)`

I'm running halotools with a custom hod model and get the error
    `TypeError: unhashable type: 'dict'`

I have managed to run the code before without getting this problem and even tested on some simple dictionaries in an ipython interpreter session myself and it seems to work:
```
In [1]: d = {"a": 1, "b": 2}

In [2]: f = {"b": 3, "c": 4}

In [3]: set(d) & set(f)
Out[3]: {'b'}
```
but these must be edge cases where the general case is still pathological. The problem with code written like this is discussed on several posts on stackoverflow, like this one: http://stackoverflow.com/questions/13264511/typeerror-unhashable-type-dict

The solution seems pretty simple, just pass the keys of the dictionaries to the sets in that line of code:

`intersection = set(self.param_dict.keys()) & set(component_model.param_dict.keys())`

I've made this change for myself and can submit a pull request with the change in a branch named "fix_sets"

**Comment by aphearin** [comment]
Thanks for catching this, @kilianbreathnach. You must be right that there must be some edge cases that don't pass the syntax I was using - these lines are repeatedly executed in my current testing suite and don't raise an exception, so it must be that your use-case is one of these edge-cases. I hope this wasn't too hard to track down. 

Good timing, too, since I'll be releasing v0.5 very soon, possibly later today.
