### ISSUE TITLE
Eliminate `new_haloprop_func_dict` mechanism

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#752]
As discussed with @mclaughlin6464 - the benefits of this mechanism are minor, and are far outweighed by the problems this causes with running MCMC chains in parallel, so this feature should be replaced immediately after the v0.5 release.

**Comment by mclaughlin6464** [comment]
@aphearin, a "quick fix" I just thought of may be to use [paritla](https://docs.python.org/2/library/functools.html). It has the same functionality that you try to implement, but should be picklable. 

I also believe that you need to use the @wraps decorator in the object as well, on the wrapper function. Not sure the exact reason why.

**Comment by mclaughlin6464** [comment]
Sorry for being a a bit late to party on this, but I just checked the latest version on master and it is not picklable. The changes made above did work, but other problems emerged. The first was `decorated_func` in `model_factory_template.py`. After a little screwing around I managed to replicate the functionality with a partial. Where should I push that change to? I noticed that the branch you had been working on was closed.

However, I still have an issue because a few objects have references to modules, specifically the four listed under this [search](https://github.com/astropy/halotools/search?utf8=%E2%9C%93&q=%22self.h5py%22&type=). It appears to be the files for caching and reading rockstar files. Is there any reason to do this? This strikes me as bad practice, but I don't think I've ever actually seen this before.
