### ISSUE TITLE
Improve documentation of Cacciato09Sats

### ISSUE THREAD

**Issue by aphearin** [astropy/halotools#765]
As per discussion with @surhudm and @johannesulf in #674.

**Comment by johannesulf** [comment]
So regarding the naming convention. I think the name Cacciato09 is justified compared to Yang08. The reason is that Yang+08 did not model the normalization of the satellite CLF as a function of halo mass. Instead, it was measured in specific bins of halo mass individually. Additionally, there's a difference in the definition of the normalization of the satellite CLF, $\phi_s^\star$. For a given $\phi_s^\star$ there's a factor of $\log(e)$ difference in the satellite occupation for Yang+08 compared to Cacciato+09. The code follows the convention of Cacciato+09.

**Comment by johannesulf** [comment]
@aphearin @surhudm I addressed this issue by expanding the docstring documentation regarding the published parameters and corresponding halo mass definitions. While I was doing that I found that I used halo_m200b as the definition, but Cacciato+09 used halo_m180b. So that was a tiny error of around 2 - 3% in halo mass. I also added the column halo_m180b to FakeSim so that all tests work with the updated Cacciato09 class. The downside of the new version is that Cacciato09 will not work out of the box with the halotools provided catalogs because they do not contain the halo_m180b column.
