### ISSUE TITLE
Halo progenitor matching

### ISSUE THREAD

**Issue by msbovill** [astropy/halotools#800]
At a given snapshot in my simulations I am trying to sum the properties of the immediate progenitors of the halos and assign that sum to the halos in the current snapshot.  Other than using crossmatch is there an efficient way to do this using halotools? I saw nothing in the online documentation which was helpful, hence the need to ask.

Mia

**Comment by aphearin** [comment]
Hi Mia,

I use the `halotools.utils.group_member_generator` all the time for the kind of calculation you're describing, though you will need to format your catalog into an astropy Table to use it.  

See if [the function's docstring](http://halotools.readthedocs.io/en/latest/api/halotools.utils.group_member_generator.html?highlight=group_member_generator) makes it clear how to do this (the final example at the end is the relevant pattern to match). You will want to use your halos descendent ID as the `grouping_key` to pre-sort your halos and group them, and then whatever quantity (or quantities) you want to sum should appear in the `requested_columns` list. 

If that's not clear, let me know.

**Comment by aphearin** [comment]
Ok, @msbovill, like I said I've done this one before, so this just took a minute for me to write out so I can hopefully save you a bit of a headache. Here goes. 

At a given snapshot, z0, suppose you wish to sum up the masses of all progenitors of each halo from the previous snapshot, z1. 

First, load the snapshot z1 into memory. You will need to know the descendent ID of each halo in z1. That is, you will need to know the z0 haloID that every object in z1 merges/descends into. Halotools does not do that for you, that will need to come from whatever halo-finder you are using  (I'm borrowing terminology from Rockstar + Consistent Trees, which does provide this, though other halo-finders provide something analogous). Let's call that array `descID_z1`. And let's call the array storing the mass of every z1 object `mass_z1`. 

To collect these arrays into an Astropy Table:

```
from astropy.table import Table
halos_z1 = Table({'descID_z1': descID_z1, 'mass_z1': mass_z1})
```

Now sort the table so that halos with a common descendant are grouped together, build the `group_member_generator`, and iterate over it:

```

halos_z1.sort('descID_z1')

grouping_key = 'descID_z1'
requested_columns = ['mass_z1']
group_gen = group_member_generator(halos_z1, grouping_key, requested_columns)

result = np.zeros(len(halos_z1))
for first, last, member_props in group_gen:
    masses = member_props[0]
    result[first:last] = np.sum(masses)
halos_z1['progenitor_mass_sum'] = result

```

For every object in z1, you now know the sum of the masses of the progenitors of their immediate descendant. 

What you asked for was to map this quantity onto the z0 objects. To do this, you will need to use the `crossmatch` function. You can cross-match the `descID_z1` column of the z1 snapshot against the `halo_ID` column of the z0 objects for this purpose. Let me know if you're not familiar with that pattern and I can sketch the pseudo-code to do it. Otherwise, make sense?

**Comment by msbovill** [comment]
Thanks, that does make sense and should be enough for me to work with.

**Comment by aphearin** [comment]
Ok, closing this Issue then. Feel free to follow up if you hit a sticking point with this solution.

**Comment by msbovill** [comment]
Hi Andrew,

Halotools installed easily and your suggestions worked well, I just want to make sure I understand exactly how everything works. I am implementing the solution and understand how the cross matching works, need a bit of clarification on exactly what the 'result' variable is. If the group_member_generator works they way I think it should len(result) = len(np.unique(halos['desc_id'])) with the result variable holding the sum of the total mass for each grouping of identical 'desc_id', but I am getting len(result) = len(halos) and am not sure about where the summing over halos with the same 'desc_id' is occuring.

Cheers,
Mia

**Comment by aphearin** [comment]
@msbovill - do you use Slack? If so, this would probably be more efficient to resolve via a quick chat rather than this GitHub Issue forum. If so, let me know your preferred contact info either by this page or by emailing me directly. If you do not use Slack, no worries, I can respond here later today or tomorrow.

**Comment by msbovill** [comment]
I just e-mailed you my slack handle.
