### ISSUE TITLE
Astropy Affiliated Package Review

### ISSUE THREAD

**Issue by astrofrog** [astropy/halotools#823]
This package has been re-reviewed by the Astropy coordination committee in relation to the Astropy affiliated package ecosystem.

We have adopted a review process for affiliated package that includes assigning quantitative ‘scores’ (red/orange/green) for different categories of review. You can read up more about this process [here](https://docs.google.com/document/d/15PJf2PROXMa7xwTDvWnjXB_9KNuO2Ia4_kkxJ7MPazE/edit). (This document, currently in Google Docs, will be moved to the documentation in the near future.) For each of the categories below we have listed the score and have included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.pch9wiwetm2l"><img src="https://img.shields.io/badge/Functionality-Specialized%20package-brightgreen.svg" alt="Specialized%20package"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Integration with Astropy ecosystem</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.lizp0k629jgg"><img src="https://img.shields.io/badge/Astropy%20integration-Partial-orange.svg" alt="Partial"></a></td></tr>

<tr><td colspan=2><i>At the time this was reviewed, it looked like integration with Quantity/Units could be improved. In addition, at the moment halotools doesn't seem to use astropy.modeling, but there may be good reasons why this is not the case. For now we have therefore scored this as 'Partial', but feel free to clarify if you think that the way it is currently could not be improved.</i></td></tr>

<tr><td><b>Documentation</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.prawoqxdnwj5"><img src="https://img.shields.io/badge/Docs-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Testing</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.8dots8fmtpvp"><img src="https://img.shields.io/badge/Tests-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Development status</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.zh2jxv4intgn"><img src="https://img.shields.io/badge/Development-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Python 3 compatibility</b></td><td><a href="https://docs.google.com/document/d/e/2PACX-1vRXvsE3m8BBo6qE5pqUMfHAfHCDgRkOy4TumaHAaAt1jXMb_jHkNFFT1ddaTHnuzlP11dZxpQ_fe_BZ/pub#h.9tur152fuipe"><img src="https://img.shields.io/badge/Python%203-Good-brightgreen.svg" alt="Good"></a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

**Summary/Decision**: Things are looking good! There are a few areas where things could be improved as described above. However, these aren't critical and this package still meets the criteria to be an affiliated package. Keep up the good work!

If you agree with the above review, please feel free to close this issue. If you have any follow-up questions or disagree with any of the comments above, leave a comment and we can discuss it here. At any point in future you can request a re-review of the package if you believe any of the scores should be updated - contact the coordination committee, and we’ll do a new review. Note that we are in the process of redesigning the http://affiliated.astropy.org page to show these scores (but not the comments). Finally, please keep the title of this issue as-is (“Astropy Affiliated Package Review”) to make it easy to search for affiliated package reviews in future.

**Comment by aphearin** [comment]
Many thanks for re-reviewing the code and providing feedback, @astrofrog and co. 

Re: Integration with Astropy ecosystem
1. Astropy Quantities remains on the wish-list of things to improve before the next major release of `v1.0` (the main new ingredient of `v1.0` is to make the package scalable to very large number of cores, which will take considerable time). I agree the package would be appreciably improved by using Units, which are quite nice. Currently, all the units are hard-coded to be the same throughout the package, with lots of repetitious and explicit statements of the units in all the docstrings. That is admittedly quite clunky. However, if I were to use to Units, I would still need all that hard-coding and repetitious documentation to make the little-h convention explicit in how units like stellar mass are defined, since this feature is currently not supported by Quantities (or has this changed?). So that does limit some of the benefit of migrating to Units. This is not a deal-breaker, I will keep Units on the `v1.0` feature list, I'm just providing feedback/explanation. If no one is working on that feature in the `astropy` development team, I should probably sign up for the task myself. 
2. I have not followed recent developments in `astropy.modeling`, though @eteq and I discussed this while the `empirical_models` sub-package was being developed, and at that time the flexibility we needed was not supported by the `modeling` features. This is certainly worth revisiting, so I raised #824 as a reminder to look into this.

**Comment by astrofrog** [comment]
@aphearin - thanks for the explanations! I think for now it probably sounds like we can leave integration as 'partial' - and if units/modeling don't provide enough flexibility, please do feel free to open issues on the core astropy repo with specific requests!
